# Generated by Django 3.0.8 on 2020-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincheck', '0002_auto_20200809_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='heading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='dislike',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
