# Generated by Django 3.0.8 on 2020-08-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincheck', '0003_auto_20200809_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
