# Generated by Django 3.0.8 on 2020-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logincheck', '0005_blogpost_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
