# Generated by Django 3.0.8 on 2020-08-12 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logincheck', '0006_auto_20200809_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
