# Generated by Django 3.0.8 on 2020-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='datetimemade',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
