# Generated by Django 3.0.8 on 2020-08-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0002_auto_20200828_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='datetimemade',
            field=models.DateTimeField(blank=True),
        ),
    ]
